spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/mercadolivro?createDatabaseIfNotExist=true
    username: root
    password:
  jackson:
    default_property_inclusion: non_null

jwt:
  secret: b3d46273-5d0d-4f0f-bd0e-b17d6cf82b0a
  expiration: 999999